version: '3'

services:
  proxy:
    build:
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - "12345:12345"
    volumes:
      - ./logs:/var/log/erss
      - ./build:/app/build
    environment:
      - TZ=America/New_York